blueprint:
  name: Prego - Wake up to configurable actions at next alarm v2.3
  description: It wakes you up with configurable actions on your phone's next alarm with a time lag. No need for phone location
  domain: automation

  #---------------
  # input
  #---------------

  input:
    in_offset:
      name: Offset
      description: Set a offset in seconds to the next alarm. When (before) the lights should turn on
      selector:
        number:
          min: 0.0
          max: 3600.0
          mode: box
          step: 1.0
          unit_of_measurement: Seconds
    in_alarm_source:
      name: Alarm Source
      description: Select the alarm source
      selector:
        entity:
          integration: mobile_app
          device_class: timestamp
          multiple: false
    in_alarm_helper:
      name: Alarm Helper
      description: Select the date time helper
      selector:
        entity:
          integration: input_datetime
          multiple: false
    in_actions:
      name: Actions
      description: Actions to run before alarm goes off
      default: []
      selector:
        action: {}

#---------------
# variables
#---------------

variables:
  offset: !input in_offset

trigger:
  - platform: time
    at: !input in_alarm_helper
    id: wake_up
  - platform: state
    entity_id:
      - !input in_alarm_source
    id: helper_update

#---------------
# Actions
#---------------

action:
  - choose:
      - conditions:
          - condition: trigger
            id: helper_update
          - condition: template
            value_template: '{{ trigger.to_state.state not in ["unknown","unavailable"] }}'
        sequence:
          - service: input_datetime.set_datetime
            data:
              timestamp: '{{ (as_timestamp(trigger.to_state.state) |int ) - (offset)}}'
            target:
              entity_id: !input in_alarm_helper
      - conditions:
          - condition: trigger
            id: wake_up
        sequence: !input in_actions
    default: []
mode: single
