# Basado en Prego-A-TargetBy-1movement.yaml
# 2025-12-12
# USO - Miguel
blueprint:
  name: Prego - Automatic switches/lights custom - By motion detection v1.3
  description: >
    Automatic switches/lights. When detecting movement - control of a switch/light (custom light switch on by script) based on motion detection and customizable conditions.
    The automation optionally includes features such as preventing activation when away from home and considering stealth mode.
  domain: automation
  #
  #---------------
  # input
  #---------------

  input:
    in_motion_sensor:
      name: Motion sensor
      description: Choose the motion sensor that covers the designated area for evaluation.
      selector:
        entity:
          domain: binary_sensor
    in_motion_sensor_keep_alive:
      name: Motion sensor (keep alive only)
      description: Optional sensor that prevents turning off the light if motion is still detected.
      default: ''
      selector:
        entity:
          domain: binary_sensor
    in_inactivity_timeout:
      name: No motion duration
      description: Time to trigger after no motion detected.
      default:
        hours: 0
        minutes: 2
        seconds: 0
      selector:
        duration: {}
    #*** Filter
    in_away_from_home:
      name: Are you away from home?
      description: Indicator signaling no one is at home (travel / away status).
      default: ''
      selector:
        entity:
          domain: input_boolean
    in_stealth_mode:
      name: Are you in stealth mode?
      description: Indicator signaling that you want to be a ninja at home (everyone sleeping / suspicious noise).
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true
    #*** Action
    in_target_entity_control:
      name: Target switch/light to control
      description: Choose the switches/lights that you want to control automatically.
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true
    in_actions_on:
      name: Actions ON
      description: Actions to run to Turn ON (custom)
      default: []
      selector:
        action: {}

#---------------
# variables
#---------------

trigger_variables:
  var_motion_sensor_keep_alive: !input in_motion_sensor_keep_alive
  var_away_from_home: !input in_away_from_home
  var_stealth_mode: !input in_stealth_mode
  var_target_entities: !input in_target_entity_control

variables:
  var_bol_motion_sensor_keep_alive: >
    {% if not var_motion_sensor_keep_alive %}
      {{ false }}
    {% else %}
      {{ is_state(var_motion_sensor_keep_alive, 'on') | bool }}
    {% endif %}
  var_bol_away_from_home: >
    {% if not var_away_from_home %}
      {{ false }}
    {% else %}
      {{ is_state(var_away_from_home, 'on') | bool }}
    {% endif %}
  var_bol_stealth_mode: >
    {% if not var_stealth_mode or (var_stealth_mode | length == 0) %}
      {{ false }}
    {% else %}
      {{
        (expand(var_stealth_mode)
          | selectattr('state', 'eq', 'on')
          | list
          | count > 0)
        | bool
      }}
    {% endif %}

#---------------
# Automation to turn ON when motion is detected.
#---------------

trigger:
  - platform: state
    entity_id: !input 'in_motion_sensor'
    id: trigger_motion_start
    to: 'on'
  - platform: state
    entity_id: !input 'in_motion_sensor'
    id: trigger_motion_end
    to: 'off'
    for: !input in_inactivity_timeout
  - platform: template
    id: trigger_motion_end_keep_alive
    value_template: >
      {% if var_motion_sensor_keep_alive is not none and var_motion_sensor_keep_alive != '' %}
        {{ is_state(var_motion_sensor_keep_alive, 'off') }}
      {% else %}
        false
      {% endif %}
    for: !input in_inactivity_timeout

#---------------
# conditions
#---------------

condition:
  - condition: template
    # Checks if at least one light is OFF (ready to turn ON)
    # Checks if at least one light is ON (ready to turn OFF)
    value_template: >
      {{
        (trigger.id == 'trigger_motion_start' and expand(var_target_entities) | selectattr('state','in',['off','unavailable','unknown']) | list | length > 0) 
        or
        (trigger.id == 'trigger_motion_end' and expand(var_target_entities) | selectattr('state', 'eq', 'on') | list | length > 0) 
        or
        (trigger.id == 'trigger_motion_end_keep_alive' and expand(var_target_entities) | selectattr('state', 'eq', 'on') | list | length > 0) 
      }}

#---------------
# Actions
#---------------

action:
  #  - service: logbook.log
  #    data:
  #      message: 'Valor de la VAR var_stealth_mode: {{ states(var_stealth_mode) }}'
  #      name: 'var_stealth_mode'
  #  - service: logbook.log
  #    data:
  #      message: 'Valor de la VAR var_bol_stealth_mode: {{ var_bol_stealth_mode }}'
  #      name: 'var_bol_stealth_mode'
  #  - service: logbook.log
  #    data:
  #      message: 'Valor de la VAR var_bol_away_from_home: {{ var_bol_away_from_home }}'
  #      name: 'var_bol_away_from_home'

  - choose:
      - alias: 'Turn ON when motion detected'
        conditions:
          #---------------
          # Case 1 - To turn ON the light when motion is detected.
          #---------------
          - condition: trigger
            id:
              - trigger_motion_start
        sequence:
          - condition: template
            value_template: '{{ not var_bol_away_from_home }}'
            # In home
          - condition: template
            value_template: '{{ not var_bol_stealth_mode }}'
            # No ninjas at home
          - condition: state
            entity_id: !input 'in_motion_sensor'
            state: 'on'
            # Motion detected
          # CUSTOM para turn ON
          - sequence: !input in_actions_on

      - alias: 'Turn OFF when no motion'
        conditions:
          #---------------
          # Case 2 - To turn OFF the light when movement is finished.
          #---------------
          - condition: trigger
            id:
              - trigger_motion_end
              - trigger_motion_end_keep_alive
        sequence:
          - condition: state
            entity_id: !input 'in_motion_sensor'
            state: 'off'
          - condition: state
            entity_id: !input 'in_motion_sensor'
            state: 'off'
            for: !input in_inactivity_timeout
          - condition: template
            value_template: '{{ not var_bol_motion_sensor_keep_alive }}'
            # keep alive is OFF
          - service: homeassistant.turn_off
            target:
              entity_id: !input 'in_target_entity_control'
          # LOG
          - service: logbook.log
            data:
              message: 'Case 2: Turn off the switch/light'
              name: 'Case RUN'

mode: single
