blueprint:
  name: Prego - Turn light on - Bulb with incremental brightness v2.1
  description: Turn on a light bulb and gradually increase its brightness until it reaches 40%.
  domain: script
  input:
    in_light_entity:
      name: Entidad de la Bombilla
      description: La entidad de la bombilla que quieres encender.
      selector:
        entity:
          domain: light
    in_transition_duration:
      name: Duración de la Transición
      description: Duración en segundos para incrementar gradualmente el brillo.
      default: 60
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: Seconds

sequence:
  - service: light.turn_on
    target:
      entity_id: !input in_light_entity
    data:
      brightness_pct: 1

  - repeat:
      count: 40
      sequence:
        - service: light.turn_on
          target:
            entity_id: !input in_light_entity
          data:
            brightness_step: 1
