blueprint:
  name: Prego - Turn switch off - By motion detection v3.7
  description: As time passes the plug goes off
  domain: automation

  input:
    in_motion_sensor:
      name: Motion sensor
      description: Select the motion sensor for the area to be evaluated.
      selector:
        entity:
          domain: binary_sensor
    in_entity_switch:
      name: Switch to control
      description: Select the switch to control automatically.
      selector:
        entity:
          domain: switch
    in_inactivity_timeout:
      name: No Motion Duration
      description: Time in seconds with no motion to trigger
      default: 120
      selector:
        number:
          min: 1
          max: 1800
          unit_of_measurement: seconds

#---------------
# Automatizacion para apagar la luz despues de un tiempo sin movimiento.
#---------------

trigger:
  platform: state
  entity_id: !input 'in_motion_sensor'
  to: 'off'
  for:
    hours: 0
    minutes: 0
    seconds: !input 'in_inactivity_timeout'

condition:
  - condition: state
    entity_id: !input 'in_entity_switch'
    state: 'on'

action:
  - service: switch.turn_off
    target:
      entity_id: !input 'in_entity_switch'
