# 2024-10-01
# USO - Miguel
blueprint:
  name: Prego - Automatic switches/lights custom - By motion detection v1.0
  description:
    Automatic switches/lights. When detecting movement - control of a switch/light (custom light switch on by script) based on motion detection and customizable conditions.
    The automation includes optionally features such as preventing activation when away from home and considering stealth mode.
  domain: automation

  #---------------
  # input
  #---------------

  input:
    in_motion_sensor:
      name: Motion sensor
      description: Choose the motion sensor that covers the designated area for evaluation.
      selector:
        entity:
          domain: binary_sensor
    in_inactivity_timeout:
      name: No Motion Duration
      description: Time in seconds with no motion to trigger
      default: 120
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: seconds
    in_away_from_home:
      name: Are you away from home?
      description: Indicator signaling the absence of occupants at home (travel status).
      default: ''
      selector:
        entity:
          domain: input_boolean
    in_stealth_mode:
      name: Are you in stealth mode?
      description: Indicator signaling that you want to be a ninja in the home (everyone sleeping / suspicious noise).
      default: ''
      selector:
        entity:
          domain: input_boolean
    in_target_entity_control:
      name: Target switch/light to control
      description: Choose the switches/lights that you want to control automatically.
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true
    in_actions_on:
      name: Actions ON
      description: Actions to run to Turn ON (custom)
      default: []
      selector:
        action: {}

#---------------
# variables
#---------------

variables:
  var_away_from_home: !input in_away_from_home
  var_stealth_mode: !input in_stealth_mode
  var_target_entities: !input in_target_entity_control
  var_bol_away_from_home: "{{ not (states(var_away_from_home) == 'off' or states(var_away_from_home) == 'unknown') }}"
  var_bol_stealth_mode: "{{ not (states(var_stealth_mode) == 'off' or states(var_stealth_mode) == 'unknown') }}"

#---------------
# Automatizacion para enceder la luz al detectar movimiento.
#---------------

trigger:
  - platform: state
    entity_id: !input 'in_motion_sensor'
    id: trigger_motion_start
    to: 'on'
  - platform: state
    entity_id: !input 'in_motion_sensor'
    id: trigger_motion_end
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: !input 'in_inactivity_timeout'

#---------------
# conditions
#---------------

condition:
  - condition: template
    # Verifica si al menos una luz está apagada (lista para encender)
    # Verifica si al menos una luz está encendida (lista para apagar)
    value_template: >
      {{
      (trigger.id == 'trigger_motion_start' and
      expand(var_target_entities) | selectattr('state', 'eq', 'off') | list | length > 0) 
      or
      (trigger.id == 'trigger_motion_end' and
      expand(var_target_entities) | selectattr('state', 'eq', 'on') | list | length > 0) 
      }}

#---------------
# Actions
#---------------

action:
  #  - service: logbook.log
  #    data:
  #      message: 'Valor de la VAR var_stealth_mode: {{ states(var_stealth_mode) }}'
  #      name: 'var_stealth_mode'
  #  - service: logbook.log
  #    data:
  #      message: 'Valor de la VAR var_bol_stealth_mode: {{ var_bol_stealth_mode }}'
  #      name: 'var_bol_stealth_mode'
  #  - service: logbook.log
  #    data:
  #      message: 'Valor de la VAR var_bol_away_from_home: {{ var_bol_away_from_home }}'
  #      name: 'var_bol_away_from_home'
  - choose:
      - conditions:
          #---------------
          # Case 1 - To turn ON the light when motion is detected.
          #---------------
          - condition: trigger
            id:
              - trigger_motion_start
          - condition: template
            value_template: '{{ not var_bol_away_from_home }}'
            # In home
          - condition: template
            value_template: '{{ not var_bol_stealth_mode }}'
            # No ninjas at home
          - condition: state
            entity_id: !input 'in_motion_sensor'
            state: 'on'
            # Motion detected
        # CUSTOM para turn ON
        sequence: !input in_actions_on
      - conditions:
          #---------------
          # Case 2 - To turn OFF the light when movement is finished.
          #---------------
          - condition: trigger
            id:
              - trigger_motion_end
          - condition: state
            entity_id: !input 'in_motion_sensor'
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input 'in_target_entity_control'
          # LOG
          - service: logbook.log
            data:
              message: 'Case 2: Turn off the switch/light'
              name: 'Case RUN'
        alias: Turn off the target
mode: single
