blueprint:
  name: Prego - Turn switch on - By motion detection v2.6
  description: When detecting movement and verifying that the variables delivered are false. The light turns on
  domain: automation

  #---------------
  # input
  #---------------

  input:
    in_motion_sensor:
      name: Motion sensor
      description: Choose the motion sensor that covers the designated area for evaluation.
      selector:
        entity:
          domain: binary_sensor
    in_away_from_home:
      name: Are you away from home?
      description: Indicator signaling the absence of occupants at home (travel status).
      selector:
        entity:
          domain: input_boolean
    in_stealth_mode:
      name: Are you in stealth mode?
      description: Indicator signaling that you want to be a ninja in the home (everyone sleeping / suspicious noise).
      selector:
        entity:
          domain: input_boolean
    in_entity_switch:
      name: Switch to control
      description: Choose the switch that you want to control automatically.
      selector:
        entity:
          domain: switch

#---------------
# Automatizacion para enceder la luz al detectar movimiento.
#---------------

trigger:
  platform: state
  entity_id: !input 'in_motion_sensor'
  to: 'on'

condition:
  - condition: state
    entity_id: !input 'in_entity_switch'
    state: 'off'
  - condition: state
    entity_id: !input 'in_away_from_home'
    state: 'off'
  - condition: state
    entity_id: !input 'in_stealth_mode'
    state: 'off'

#---------------
# Actions
#---------------

action:
  - service: switch.turn_on
    target:
      entity_id: !input 'in_entity_switch'
