# 2025-11-11
blueprint:
  name: Prego - Config Wake up to configurable actions at next alarm v2.8
  description: Automate actions before an alarm, using a specific time interval and selected alarm sources to trigger events such as turning on lights. You don't need the location of the phone.
  domain: automation

  #---------------
  # input
  #---------------

  input:
    in_offset:
      name: Offset
      description: Set a offset in seconds to the next alarm. When (before) the lights should turn on
      default: 10
      selector:
        number:
          min: 0.0
          max: 3600.0
          mode: box
          step: 1.0
          unit_of_measurement: seconds
    in_alarm_source:
      name: Alarm Source
      description: Select the alarm source
      selector:
        entity:
          integration: mobile_app
          device_class: timestamp
          multiple: false
    in_alarm_helper:
      name: Alarm Helper
      description: Select the date time helper
      selector:
        entity:
          integration: input_datetime
          multiple: false
    #*** Filter
    in_away_from_home:
      name: Are you away from home?
      description: Indicator signaling no one is at home (travel / away status).
      default: ''
      selector:
        entity:
          domain: input_boolean
    in_stealth_mode:
      name: Are you in stealth mode?
      description: Indicator signaling that you want to be a ninja at home (everyone sleeping / suspicious noise).
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: true
    #*** Action
    in_actions:
      name: Actions
      description: Actions to run before alarm goes off
      default: []
      selector:
        action: {}

#---------------
# variables
#---------------

variables:
  offset: !input in_offset
  var_away_from_home: !input in_away_from_home
  var_stealth_mode: !input in_stealth_mode
  var_bol_away_from_home: >
    {% if not var_away_from_home %}
      {{ false }}
    {% else %}
      {{ is_state(var_away_from_home, 'on') | bool }}
    {% endif %}
  var_bol_stealth_mode: >
    {% if not var_stealth_mode or (var_stealth_mode | length == 0) %}
      {{ false }}
    {% else %}
      {{
        (expand(var_stealth_mode)
          | selectattr('state', 'eq', 'on')
          | list
          | count > 0)
        | bool
      }}
    {% endif %}

trigger:
  - platform: time
    at: !input in_alarm_helper
    id: wake_up
  - platform: state
    entity_id:
      - !input in_alarm_source
    id: helper_update

#---------------
# Actions
#---------------

action:
  - choose:
      - alias: 'Set helper datetime offset'
        conditions:
          - condition: trigger
            id: helper_update
          - condition: template
            value_template: >
              {% set new_state = trigger.to_state.state %}
              {{ new_state is not none and new_state not in ["unknown", "unavailable"] }}
        sequence:
          - service: input_datetime.set_datetime
            data:
              timestamp: >
                {{ (as_timestamp(trigger.to_state.state) | int) - offset }}
            target:
              entity_id: !input in_alarm_helper

      - alias: 'Execute wake-up actions'
        conditions:
          - condition: trigger
            id: wake_up
        sequence:
          - condition: template
            value_template: '{{ not var_bol_away_from_home }}'
            # In home
          - condition: template
            value_template: '{{ not var_bol_stealth_mode }}'
            # No ninjas at home
          - sequence: !input in_actions
    default: []

mode: single
