# 2024-10-06
blueprint:
  name: Prego - Config Lack of sunlight - By sun prego v0.2
  description:
    Config - defines the boolean for the lack of light, guided by the sunrise and sunset settings -- lack of sunlight.
    The automation includes optionally features such as preventing activation when away from home and considering stealth mode.
  domain: automation

  #---------------
  # input
  #---------------

  input:
    in_away_from_home:
      name: Are you away from home?
      description: Indicator signaling the absence of occupants at home (travel status).
      default: ''
      selector:
        entity:
          domain: input_boolean
    in_stealth_mode:
      name: Are you in stealth mode?
      description: Indicator signaling that you want to be a ninja in the home (everyone sleeping / suspicious noise).
      default: ''
      selector:
        entity:
          domain: input_boolean
    in_time_morning:
      name: Sunrise Helper
      description: Choose the time helper corresponding to sunrise.
      selector:
        entity:
          integration: input_datetime
          multiple: false
    in_time_night:
      name: Sunset Helper
      description: Choose the time helper corresponding to Sunset.
      selector:
        entity:
          integration: input_datetime
          multiple: false
    in_target_entity_control:
      name: Property to reflect the need for light
      description: Boolean defining Lack of sunlight.
      selector:
        entity:
          domain:
            input_boolean

#---------------
# variables
#---------------

variables:
  var_away_from_home: !input in_away_from_home
  var_stealth_mode: !input in_stealth_mode
  var_target_entities: !input in_target_entity_control
  var_bol_away_from_home: "{{ not (states(var_away_from_home) == 'off' or states(var_away_from_home) == 'unknown') }}"
  var_bol_stealth_mode: "{{ not (states(var_stealth_mode) == 'off' or states(var_stealth_mode) == 'unknown') }}"

#---------------
# Automatizacion para enceder la luz al detectar movimiento.
#---------------

trigger:
  - platform: time
    id: trigger_time_morning
    at: !input 'in_time_morning'
  - platform: time
    id: trigger_time_night
    at: !input 'in_time_night'
  - platform: state
    entity_id: !input 'in_away_from_home'
    id: trigger_state_away_on
    to: 'on'

#---------------
# conditions
#---------------

condition:

#---------------
# Actions
#---------------

action:
  - choose:
      - conditions:
          #---------------
          # Case 1 - To turn ON the light when motion is detected.
          #---------------
          - condition: trigger
            id:
              - trigger_time_night
          - condition: template
            value_template: '{{ not var_bol_away_from_home }}'
            # In home
          - condition: template
            value_template: '{{ not var_bol_stealth_mode }}'
            # No ninjas at home
          - condition: or
            conditions:
              - condition: time
                after: !input 'in_time_night'
                # After time
              - condition: time
                before: !input 'in_time_morning'
                # Before time
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input 'in_target_entity_control'
        alias: Turn on the target
      - conditions:
          #---------------
          # Case 2 - To turn OFF the light when movement is finished.
          #---------------
          - condition: trigger
            id:
              - trigger_state_away_on
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input 'in_target_entity_control'
        alias: Turn off the target
      - conditions:
          #---------------
          # Case 3 - To turn OFF the light when there is daylight.
          #---------------
          - condition: trigger
            id:
              - trigger_time_morning
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input 'in_target_entity_control'
        alias: Turn off the target - it's already morning!
mode: single
