# 2025-11-22
blueprint:
  name: Prego - Config Automatic Termo - By Time and Person v0.11
  description: >
    # 🔆 Config electric water heater switch

  domain: automation

  #---------------
  # input
  #---------------

  input:
    #*** Filter
    in_away_from_home:
      name: Are you away from home?
      description: Indicator signaling no one is at home (travel / away status).
      default: ''
      selector:
        entity:
          domain: input_boolean
    #*** Action
    in_target_entity_control:
      name: Electric water heater switch
      description: Electric water heater (Termo) switch entity
      selector:
        entity:
          domain: switch

#---------------
# triggers
#---------------

trigger:
  #--- Todos los dias - Mornings
  - platform: time
    at: '00:10:00'
    id: M_off
  - platform: time
    at: '03:00:00'
    id: M_on_1
  - platform: time
    at: '04:30:00'
    id: M_off_1
  #--- Dias dentro de Semana
  - platform: time
    at: '06:30:00'
    id: week_M_1_on
  - platform: time
    at: '08:00:00'
    id: week_M_1_off
  - platform: time
    at: '11:15:00'
    id: week_M_2_on
  - platform: time
    at: '12:45:00'
    id: week_M_2_off
  #--- FIN de Semana
  - platform: time
    at: '07:35:00'
    id: finSem_M_1_on
  - platform: time
    at: '11:20:00'
    id: finSem_M_1_off
  #--- Todos los dias Afternoon
  - platform: time
    at: '14:00:00'
    id: T_on_1
  - platform: time
    at: '15:45:00'
    id: T_off_1
  - platform: time
    at: '18:00:00'
    id: T_on_2
  - platform: time
    at: '19:00:00'
    id: T_off_2
  - platform: time
    at: '20:00:00'
    id: T_on_3
  - platform: time
    at: '20:30:00'
    id: T_off_3
  - platform: time
    at: '21:00:00'
    id: T_off

#---------------
# variables
#---------------

variables:
  var_away_from_home: !input in_away_from_home
  var_target_entities: !input in_target_entity_control
  var_bol_away_from_home: >
    {% if not var_away_from_home %}
      {{ false }}
    {% else %}
      {{ is_state(var_away_from_home, 'on') | bool }}
    {% endif %}
  is_weekend: >
    {{ now().weekday() in [5, 6] }}

#---------------
# actions
#---------------

action:
  # Comun todos los dias
  - choose:
      - conditions:
          #---------------
          # Case ON 1 - To turn ON the Termo.
          #---------------
          - condition: trigger
            id:
              - M_on_1
              - T_on_1
              - T_on_2
              - T_on_3
        sequence:
          - condition: template
            value_template: '{{ not var_bol_away_from_home }}'
            # In home
          - condition: state
            entity_id: !input 'in_target_entity_control'
            state: 'off'
            # is OFF el estado actual
          - service: homeassistant.turn_on
            target:
              entity_id: !input 'in_target_entity_control'
          # LOG
          - service: logbook.log
            data:
              message: 'Case 1: Turn on the switch/Termo'
              name: 'Termo'
        alias: Turn on the target
      - conditions:
          #---------------
          # Case 2 - To turn OFF the Termo when time is finished.
          #---------------
          - condition: trigger
            id:
              - M_off
              - M_off_1
              - T_off_1
              - T_off_2
              - T_off_3
              - T_off
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input 'in_target_entity_control'
          # LOG
          - service: logbook.log
            data:
              message: 'Case 2: Turn off the switch/Termo'
              name: 'Termo'
        alias: Turn off the target

  - if:
      - condition: template
        value_template: "{{ is_weekend }}"
    then:
      # is weekend
      - choose:
          - conditions:
              #---------------
              # Case 1 - To turn ON the Termo when Sat and Sun.
              #---------------
              - condition: trigger
                id:
                  - finSem_M_1_on
            sequence:
              - condition: template
                value_template: '{{ not var_bol_away_from_home }}'
                # In home
              - condition: state
                entity_id: !input 'in_target_entity_control'
                state: 'off'
                # is OFF el estado actual
              - service: homeassistant.turn_on
                target:
                  entity_id: !input 'in_target_entity_control'
              # LOG
              - service: logbook.log
                data:
                  message: 'Case 1: Turn on the switch/Termo weekend'
                  name: 'Termo'
            alias: Turn on the target
          - conditions:
              #---------------
              # Case 2 - To turn OFF the Termo when time is finished (weekend).
              #---------------
              - condition: trigger
                id:
                  - finSem_M_1_off
            sequence:
              - service: homeassistant.turn_off
                target:
                  entity_id: !input 'in_target_entity_control'
              # LOG
              - service: logbook.log
                data:
                  message: 'Case 2: Turn off the switch/Termo weekend'
                  name: 'Termo'
            alias: Turn off the target
    else:
      # is NOT weekend (Mon–Fri)
      - choose:
          - conditions:
              #---------------
              # Case 1 - To turn ON the Termo when M-F.
              #---------------
              - condition: trigger
                id:
                  - week_M_1_on
                  - week_M_2_on
            sequence:
              - condition: template
                value_template: '{{ not var_bol_away_from_home }}'
                # In home
              - condition: state
                entity_id: !input 'in_target_entity_control'
                state: 'off'
                # is OFF el estado actual
              - service: homeassistant.turn_on
                target:
                  entity_id: !input 'in_target_entity_control'
              # LOG
              - service: logbook.log
                data:
                  message: 'Case 1: Turn on the switch/Termo M-F'
                  name: 'Termo'
            alias: Turn on the target
          - conditions:
              #---------------
              # Case 2 - To turn OFF the Termo when time is finished (weekdays).
              #---------------
              - condition: trigger
                id:
                  - week_M_1_off
                  - week_M_2_off
            sequence:
              - service: homeassistant.turn_off
                target:
                  entity_id: !input 'in_target_entity_control'
              # LOG
              - service: logbook.log
                data:
                  message: 'Case 2: Turn off the switch/Termo weekdays'
                  name: 'Termo'
            alias: Turn off the target

mode: single
