# 2024-04-19
blueprint:
  name: Prego - Turn off switch/light - By motion detection v3.11
  description: Automate lights or switches to turn off when no motion is detected for a specified duration in a designated area.
  domain: automation

  input:
    in_motion_sensor:
      name: Motion sensor
      description: Choose the motion sensor that covers the designated area for evaluation.
      selector:
        entity:
          domain: binary_sensor
    in_inactivity_timeout:
      name: No Motion Duration
      description: Time in seconds with no motion to trigger
      default: 120
      selector:
        number:
          min: 1
          max: 1200
          unit_of_measurement: seconds
    in_target_entity_control:
      name: Target switch/light to control
      description: Choose the switch/light that you want to control automatically.
      selector:
        entity:
          domain:
            - switch
            - light


trigger:
  platform: state
  entity_id: !input 'in_motion_sensor'
  to: 'off'
  for:
    hours: 0
    minutes: 0
    seconds: !input 'in_inactivity_timeout'

condition:
  - condition: state
    entity_id: !input 'in_target_entity_control'
    state: 'on'



action:
  - service: homeassistant.turn_off
    entity_id: !input 'in_target_entity_control'
