# Deprecado psar a usar --> Prego-A-TargetBy-1movement.yaml
# 2024-04-19
blueprint:
  name: Prego Old - Turn on switch/light - By motion detection v2.9
  description: Automate lights or switches to turn on based on motion detection, ensuring it only activates when you are home and not in stealth mode.
  domain: automation

  #---------------
  # input
  #---------------

  input:
    in_motion_sensor:
      name: Motion sensor
      description: Choose the motion sensor that covers the designated area for evaluation.
      selector:
        entity:
          domain: binary_sensor
    in_away_from_home:
      name: Are you away from home?
      description: Indicator signaling the absence of occupants at home (travel status).
      default: ''
      selector:
        entity:
          domain: input_boolean
    in_stealth_mode:
      name: Are you in stealth mode?
      description: Indicator signaling that you want to be a ninja in the home (everyone sleeping / suspicious noise).
      default: ''
      selector:
        entity:
          domain: input_boolean
    in_target_entity_control:
      name: Switch to control
      description: Choose the switch that you want to control automatically.
      selector:
        entity:
          domain: switch

#---------------
# variables
#---------------

variables:
  var_away_from_home: !input in_away_from_home
  var_stealth_mode: !input in_stealth_mode
  var_bol_away_from_home: "{{ not (states(var_away_from_home) == 'off' or states(var_away_from_home) == 'unknown') }}"
  var_bol_stealth_mode: "{{ not (states(var_stealth_mode) == 'off' or states(var_stealth_mode) == 'unknown') }}"

#---------------
# Automatizacion para enceder la luz al detectar movimiento.
#---------------

trigger:
  platform: state
  entity_id: !input 'in_motion_sensor'
  to: 'on'

condition:
  - condition: template
    value_template: '{{ not var_bol_away_from_home }}'
    # In home
  - condition: template
    value_template: '{{ not var_bol_stealth_mode }}'
    # No ninjas at home
  - condition: state
    entity_id: !input 'in_target_entity_control'
    state: 'off'

#---------------
# Actions
#---------------

action:
  - service: homeassistant.turn_on
    entity_id: !input 'in_target_entity_control'
